import type { ProjectConfig, PresetDefinition } from "@ploybundle/shared";

export function renderNextjsPackageJson(config: ProjectConfig, _preset: PresetDefinition): string {
  const pkg = {
    name: `@${config.projectName}/app`,
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start -p 3000",
      lint: "next lint",
    },
    dependencies: {
      next: "^14.2.0",
      react: "^18.3.0",
      "react-dom": "^18.3.0",
    },
    devDependencies: {
      "@types/node": "^20.14.0",
      "@types/react": "^18.3.0",
      "@types/react-dom": "^18.3.0",
      typescript: "^5.5.0",
    },
  };

  return JSON.stringify(pkg, null, 2);
}

export function renderNextjsConfig(config: ProjectConfig): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = {
  output: "standalone",
  experimental: {
    serverActions: {
      bodySizeLimit: "2mb",
    },
  },
  images: {
    remotePatterns: [
      {
        protocol: "https",
        hostname: "${config.domain.storage ?? `storage.${config.domain.root}`}",
      },
    ],
  },
};

module.exports = nextConfig;
`;
}

export function renderNextjsTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "es2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./src/*"] },
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"],
    },
    null,
    2
  );
}

export function renderNextjsLayout(config: ProjectConfig, preset: PresetDefinition): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${preset.displayName} - ${config.projectName}",
  description: "${preset.description}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

export function renderNextjsGlobalsCss(): string {
  return `*,
*::before,
*::after {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

:root {
  --foreground: #171717;
  --background: #ffffff;
  --primary: #2563eb;
  --primary-light: #3b82f6;
  --muted: #6b7280;
  --border: #e5e7eb;
  --radius: 8px;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  color: var(--foreground);
  background: var(--background);
  line-height: 1.6;
}

a {
  color: var(--primary);
  text-decoration: none;
}

a:hover {
  text-decoration: underline;
}
`;
}

export function renderNextjsHomePage(config: ProjectConfig, preset: PresetDefinition): string {
  const features = preset.nextjsFeatures
    .map((f) => `          <li key="${f}">${f.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())}</li>`)
    .join("\n");

  return `export default function Home() {
  return (
    <main style={{ maxWidth: 800, margin: "0 auto", padding: "2rem" }}>
      <h1>${preset.displayName}</h1>
      <p style={{ color: "var(--muted)", marginBottom: "2rem" }}>
        ${preset.description}
      </p>

      <section style={{ marginBottom: "2rem" }}>
        <h2>Project: ${config.projectName}</h2>
        <p>Preset: ${preset.name} | Target: ${config.target}</p>
      </section>

      <section style={{ marginBottom: "2rem" }}>
        <h2>Features</h2>
        <ul style={{ paddingLeft: "1.5rem" }}>
${features}
        </ul>
      </section>

      <section>
        <h2>Quick Links</h2>
        <ul style={{ paddingLeft: "1.5rem" }}>
          <li><a href="/api/health">Health Check API</a></li>
        </ul>
      </section>
    </main>
  );
}
`;
}

export function renderNextjsHealthRoute(): string {
  return `import { NextResponse } from "next/server";

export async function GET() {
  const health = {
    status: "ok",
    timestamp: new Date().toISOString(),
    uptime: process.uptime(),
    env: process.env.NODE_ENV,
  };

  return NextResponse.json(health);
}
`;
}

export function renderNextjsEnvLocal(config: ProjectConfig): string {
  return `# Auto-generated by ploybundle - do not edit directly
# Use ploybundle.yaml to manage configuration

# App
NEXT_PUBLIC_APP_URL=https://${config.domain.app ?? config.domain.root}
NEXT_PUBLIC_API_URL=https://${config.domain.app ?? config.domain.root}/api

# Directus
NEXT_PUBLIC_DIRECTUS_URL=https://${config.domain.admin ?? `admin.${config.domain.root}`}
DIRECTUS_URL=http://directus:8055
DIRECTUS_TOKEN=\${DIRECTUS_ADMIN_TOKEN}

# Storage
NEXT_PUBLIC_STORAGE_URL=https://${config.domain.storage ?? `storage.${config.domain.root}`}

# Auth
NEXTAUTH_URL=https://${config.domain.app ?? config.domain.root}
NEXTAUTH_SECRET=\${NEXTAUTH_SECRET}

# Database
DATABASE_URL=\${DATABASE_URL}

# Redis
REDIS_URL=\${REDIS_URL}
`;
}
